# /Users/geoffreygarrett/Repositories/nsri-link/packages/keyflux/Cargo.toml

[workspace]
members = [
    "keyflux_macros",
    "keyflux_curl",
    "keyflux", "keyflux_postgres",
]


resolver = "1"

# Optionally, specify some default features
#default = ["curl", "macro"]
