/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ActionsListJobsForWorkflowRunAttempt200Response {
    #[serde(rename = "total_count")]
    pub total_count: i32,
    #[serde(rename = "jobs")]
    pub jobs: Vec<crate::models::Job>,
}

impl ActionsListJobsForWorkflowRunAttempt200Response {
    pub fn new(total_count: i32, jobs: Vec<crate::models::Job>) -> ActionsListJobsForWorkflowRunAttempt200Response {
        ActionsListJobsForWorkflowRunAttempt200Response {
            total_count,
            jobs,
        }
    }
}


