/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CodeScanningAlertSetState : Sets the state of the code scanning alert. You must provide `dismissed_reason` when you set the state to `dismissed`.

/// Sets the state of the code scanning alert. You must provide `dismissed_reason` when you set the state to `dismissed`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CodeScanningAlertSetState {
    #[serde(rename = "open")]
    Open,
    #[serde(rename = "dismissed")]
    Dismissed,

}

impl ToString for CodeScanningAlertSetState {
    fn to_string(&self) -> String {
        match self {
            Self::Open => String::from("open"),
            Self::Dismissed => String::from("dismissed"),
        }
    }
}

impl Default for CodeScanningAlertSetState {
    fn default() -> CodeScanningAlertSetState {
        Self::Open
    }
}




