/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Committer1 : Metaproperties for Git author/committer information.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Committer1 {
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// The git author's name.
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
}

impl Committer1 {
    /// Metaproperties for Git author/committer information.
    pub fn new(name: String) -> Committer1 {
        Committer1 {
            date: None,
            email: None,
            name,
            username: None,
        }
    }
}


