/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// FileCommit : File Commit



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FileCommit {
    #[serde(rename = "content")]
    pub content: Option<Box<crate::models::FileCommitContent>>,
    #[serde(rename = "commit")]
    pub commit: Box<crate::models::FileCommitCommit>,
}

impl FileCommit {
    /// File Commit
    pub fn new(content: Option<crate::models::FileCommitContent>, commit: crate::models::FileCommitCommit) -> FileCommit {
        FileCommit {
            content: if let Some(x) = content {Some(Box::new(x))} else {None},
            commit: Box::new(commit),
        }
    }
}


