/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// OidcCustomSub : Actions OIDC Subject customization



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OidcCustomSub {
    /// Array of unique strings. Each claim key can only contain alphanumeric characters and underscores.
    #[serde(rename = "include_claim_keys")]
    pub include_claim_keys: Vec<String>,
}

impl OidcCustomSub {
    /// Actions OIDC Subject customization
    pub fn new(include_claim_keys: Vec<String>) -> OidcCustomSub {
        OidcCustomSub {
            include_claim_keys,
        }
    }
}


