/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PullRequestMinimal {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "number")]
    pub number: i32,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "head")]
    pub head: Box<crate::models::PullRequestMinimalHead>,
    #[serde(rename = "base")]
    pub base: Box<crate::models::PullRequestMinimalHead>,
}

impl PullRequestMinimal {
    pub fn new(id: i64, number: i32, url: String, head: crate::models::PullRequestMinimalHead, base: crate::models::PullRequestMinimalHead) -> PullRequestMinimal {
        PullRequestMinimal {
            id,
            number,
            url,
            head: Box::new(head),
            base: Box::new(base),
        }
    }
}


