/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RepositoryAdvisoryCreate {
    /// A short summary of the advisory.
    #[serde(rename = "summary")]
    pub summary: String,
    /// A detailed description of what the advisory impacts.
    #[serde(rename = "description")]
    pub description: String,
    /// The Common Vulnerabilities and Exposures (CVE) ID.
    #[serde(rename = "cve_id", skip_serializing_if = "Option::is_none")]
    pub cve_id: Option<String>,
    /// A product affected by the vulnerability detailed in a repository security advisory.
    #[serde(rename = "vulnerabilities")]
    pub vulnerabilities: Vec<crate::models::RepositoryAdvisoryCreateVulnerabilitiesInner>,
    /// A list of Common Weakness Enumeration (CWE) IDs.
    #[serde(rename = "cwe_ids", skip_serializing_if = "Option::is_none")]
    pub cwe_ids: Option<Vec<String>>,
    /// A list of users receiving credit for their participation in the security advisory.
    #[serde(rename = "credits", skip_serializing_if = "Option::is_none")]
    pub credits: Option<Vec<crate::models::RepositoryAdvisoryCreateCreditsInner>>,
    /// The severity of the advisory. You must choose between setting this field or `cvss_vector_string`.
    #[serde(rename = "severity", skip_serializing_if = "Option::is_none")]
    pub severity: Option<Severity>,
    /// The CVSS vector that calculates the severity of the advisory. You must choose between setting this field or `severity`.
    #[serde(rename = "cvss_vector_string", skip_serializing_if = "Option::is_none")]
    pub cvss_vector_string: Option<String>,
    /// Whether to create a temporary private fork of the repository to collaborate on a fix.
    #[serde(rename = "start_private_fork", skip_serializing_if = "Option::is_none")]
    pub start_private_fork: Option<bool>,
}

impl RepositoryAdvisoryCreate {
    pub fn new(summary: String, description: String, vulnerabilities: Vec<crate::models::RepositoryAdvisoryCreateVulnerabilitiesInner>) -> RepositoryAdvisoryCreate {
        RepositoryAdvisoryCreate {
            summary,
            description,
            cve_id: None,
            vulnerabilities,
            cwe_ids: None,
            credits: None,
            severity: None,
            cvss_vector_string: None,
            start_private_fork: None,
        }
    }
}

/// The severity of the advisory. You must choose between setting this field or `cvss_vector_string`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Severity {
    #[serde(rename = "critical")]
    Critical,
    #[serde(rename = "high")]
    High,
    #[serde(rename = "medium")]
    Medium,
    #[serde(rename = "low")]
    Low,
}

impl Default for Severity {
    fn default() -> Severity {
        Self::Critical
    }
}

