/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RepositoryAdvisoryCreateVulnerabilitiesInnerPackage : The name of the package affected by the vulnerability.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RepositoryAdvisoryCreateVulnerabilitiesInnerPackage {
    #[serde(rename = "ecosystem")]
    pub ecosystem: crate::models::SecurityAdvisoryEcosystems,
    /// The unique package name within its ecosystem.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl RepositoryAdvisoryCreateVulnerabilitiesInnerPackage {
    /// The name of the package affected by the vulnerability.
    pub fn new(ecosystem: crate::models::SecurityAdvisoryEcosystems) -> RepositoryAdvisoryCreateVulnerabilitiesInnerPackage {
        RepositoryAdvisoryCreateVulnerabilitiesInnerPackage {
            ecosystem,
            name: None,
        }
    }
}


