/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RepositoryRuleCommitMessagePattern : Parameters to be used for the commit_message_pattern rule



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RepositoryRuleCommitMessagePattern {
    #[serde(rename = "type")]
    pub r#type: RHashType,
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<Box<crate::models::RepositoryRuleCommitMessagePatternParameters>>,
}

impl RepositoryRuleCommitMessagePattern {
    /// Parameters to be used for the commit_message_pattern rule
    pub fn new(r#type: RHashType) -> RepositoryRuleCommitMessagePattern {
        RepositoryRuleCommitMessagePattern {
            r#type,
            parameters: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "commit_message_pattern")]
    CommitMessagePattern,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::CommitMessagePattern
    }
}

