/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RepositoryRuleDeletion : Only allow users with bypass permissions to delete matching refs.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RepositoryRuleDeletion {
    #[serde(rename = "type")]
    pub r#type: RHashType,
}

impl RepositoryRuleDeletion {
    /// Only allow users with bypass permissions to delete matching refs.
    pub fn new(r#type: RHashType) -> RepositoryRuleDeletion {
        RepositoryRuleDeletion {
            r#type,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "deletion")]
    Deletion,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::Deletion
    }
}

