/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Runner : A self hosted runner



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Runner {
    /// The id of the runner.
    #[serde(rename = "id")]
    pub id: i32,
    /// The id of the runner group.
    #[serde(rename = "runner_group_id", skip_serializing_if = "Option::is_none")]
    pub runner_group_id: Option<i32>,
    /// The name of the runner.
    #[serde(rename = "name")]
    pub name: String,
    /// The Operating System of the runner.
    #[serde(rename = "os")]
    pub os: String,
    /// The status of the runner.
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "busy")]
    pub busy: bool,
    #[serde(rename = "labels")]
    pub labels: Vec<crate::models::RunnerLabel>,
}

impl Runner {
    /// A self hosted runner
    pub fn new(id: i32, name: String, os: String, status: String, busy: bool, labels: Vec<crate::models::RunnerLabel>) -> Runner {
        Runner {
            id,
            runner_group_id: None,
            name,
            os,
            status,
            busy,
            labels,
        }
    }
}


