/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SecretScanningUpdateAlertRequest {
    #[serde(rename = "state")]
    pub state: crate::models::SecretScanningAlertState,
    #[serde(rename = "resolution", skip_serializing_if = "Option::is_none")]
    pub resolution: Option<crate::models::SecretScanningAlertResolution>,
    /// An optional comment when closing an alert. Cannot be updated or deleted. Must be `null` when changing `state` to `open`.
    #[serde(rename = "resolution_comment", skip_serializing_if = "Option::is_none")]
    pub resolution_comment: Option<String>,
}

impl SecretScanningUpdateAlertRequest {
    pub fn new(state: crate::models::SecretScanningAlertState) -> SecretScanningUpdateAlertRequest {
        SecretScanningUpdateAlertRequest {
            state,
            resolution: None,
            resolution_comment: None,
        }
    }
}


