/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SigstoreBundle0DsseEnvelope {
    #[serde(rename = "payload", skip_serializing_if = "Option::is_none")]
    pub payload: Option<String>,
    #[serde(rename = "payloadType", skip_serializing_if = "Option::is_none")]
    pub payload_type: Option<String>,
    #[serde(rename = "signatures", skip_serializing_if = "Option::is_none")]
    pub signatures: Option<Vec<crate::models::SigstoreBundle0DsseEnvelopeSignaturesInner>>,
}

impl SigstoreBundle0DsseEnvelope {
    pub fn new() -> SigstoreBundle0DsseEnvelope {
        SigstoreBundle0DsseEnvelope {
            payload: None,
            payload_type: None,
            signatures: None,
        }
    }
}


