/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// WebhooksRepositorySelection : Describe whether all repositories have been selected or there's a selection involved

/// Describe whether all repositories have been selected or there's a selection involved
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WebhooksRepositorySelection {
    #[serde(rename = "all")]
    All,
    #[serde(rename = "selected")]
    Selected,

}

impl ToString for WebhooksRepositorySelection {
    fn to_string(&self) -> String {
        match self {
            Self::All => String::from("all"),
            Self::Selected => String::from("selected"),
        }
    }
}

impl Default for WebhooksRepositorySelection {
    fn default() -> WebhooksRepositorySelection {
        Self::All
    }
}




