/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WebhookIssuesTransferredChanges {
    #[serde(rename = "new_issue")]
    pub new_issue: Box<crate::models::Issue13>,
    #[serde(rename = "new_repository")]
    pub new_repository: Box<crate::models::Repository3>,
}

impl WebhookIssuesTransferredChanges {
    pub fn new(new_issue: crate::models::Issue13, new_repository: crate::models::Repository3) -> WebhookIssuesTransferredChanges {
        WebhookIssuesTransferredChanges {
            new_issue: Box::new(new_issue),
            new_repository: Box::new(new_repository),
        }
    }
}


