/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WebhookSponsorshipPendingTierChange {
    #[serde(rename = "action")]
    pub action: Action,
    #[serde(rename = "changes")]
    pub changes: Box<crate::models::WebhooksChanges8>,
    /// The `pending_cancellation` and `pending_tier_change` event types will include the date the cancellation or tier change will take effect.
    #[serde(rename = "effective_date", skip_serializing_if = "Option::is_none")]
    pub effective_date: Option<String>,
    #[serde(rename = "enterprise", skip_serializing_if = "Option::is_none")]
    pub enterprise: Option<Box<crate::models::EnterpriseWebhooks>>,
    #[serde(rename = "installation", skip_serializing_if = "Option::is_none")]
    pub installation: Option<Box<crate::models::SimpleInstallation>>,
    #[serde(rename = "organization", skip_serializing_if = "Option::is_none")]
    pub organization: Option<Box<crate::models::OrganizationSimpleWebhooks>>,
    #[serde(rename = "repository", skip_serializing_if = "Option::is_none")]
    pub repository: Option<Box<crate::models::RepositoryWebhooks>>,
    #[serde(rename = "sender")]
    pub sender: Box<crate::models::SimpleUserWebhooks>,
    #[serde(rename = "sponsorship")]
    pub sponsorship: Box<crate::models::WebhooksSponsorship>,
}

impl WebhookSponsorshipPendingTierChange {
    pub fn new(action: Action, changes: crate::models::WebhooksChanges8, sender: crate::models::SimpleUserWebhooks, sponsorship: crate::models::WebhooksSponsorship) -> WebhookSponsorshipPendingTierChange {
        WebhookSponsorshipPendingTierChange {
            action,
            changes: Box::new(changes),
            effective_date: None,
            enterprise: None,
            installation: None,
            organization: None,
            repository: None,
            sender: Box::new(sender),
            sponsorship: Box::new(sponsorship),
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Action {
    #[serde(rename = "pending_tier_change")]
    PendingTierChange,
}

impl Default for Action {
    fn default() -> Action {
        Self::PendingTierChange
    }
}

