/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WebhookRegistryPackagePublishedRegistryPackagePackageVersionContainerMetadata {
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<serde_json::Value>,
    #[serde(rename = "manifest", skip_serializing_if = "Option::is_none")]
    pub manifest: Option<serde_json::Value>,
    #[serde(rename = "tag", skip_serializing_if = "Option::is_none")]
    pub tag: Option<Box<crate::models::WebhookPackagePublishedPackagePackageVersionContainerMetadataTag>>,
}

impl WebhookRegistryPackagePublishedRegistryPackagePackageVersionContainerMetadata {
    pub fn new() -> WebhookRegistryPackagePublishedRegistryPackagePackageVersionContainerMetadata {
        WebhookRegistryPackagePublishedRegistryPackagePackageVersionContainerMetadata {
            labels: None,
            manifest: None,
            tag: None,
        }
    }
}


