/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// WebhookProjectEditedChanges : The changes to the project if the action was `edited`.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WebhookProjectEditedChanges {
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<Box<crate::models::WebhookProjectEditedChangesBody>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<Box<crate::models::WebhookProjectEditedChangesName>>,
}

impl WebhookProjectEditedChanges {
    /// The changes to the project if the action was `edited`.
    pub fn new() -> WebhookProjectEditedChanges {
        WebhookProjectEditedChanges {
            body: None,
            name: None,
        }
    }
}


