/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WebhookRepositoryDispatchSample {
    /// The `event_type` that was specified in the `POST /repos/{owner}/{repo}/dispatches` request body.
    #[serde(rename = "action")]
    pub action: String,
    #[serde(rename = "branch")]
    pub branch: String,
    /// The `client_payload` that was specified in the `POST /repos/{owner}/{repo}/dispatches` request body.
    #[serde(rename = "client_payload")]
    pub client_payload: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "enterprise", skip_serializing_if = "Option::is_none")]
    pub enterprise: Option<Box<crate::models::EnterpriseWebhooks>>,
    #[serde(rename = "installation")]
    pub installation: Box<crate::models::SimpleInstallation>,
    #[serde(rename = "organization", skip_serializing_if = "Option::is_none")]
    pub organization: Option<Box<crate::models::OrganizationSimpleWebhooks>>,
    #[serde(rename = "repository")]
    pub repository: Box<crate::models::RepositoryWebhooks>,
    #[serde(rename = "sender")]
    pub sender: Box<crate::models::SimpleUserWebhooks>,
}

impl WebhookRepositoryDispatchSample {
    pub fn new(action: String, branch: String, client_payload: Option<::std::collections::HashMap<String, serde_json::Value>>, installation: crate::models::SimpleInstallation, repository: crate::models::RepositoryWebhooks, sender: crate::models::SimpleUserWebhooks) -> WebhookRepositoryDispatchSample {
        WebhookRepositoryDispatchSample {
            action,
            branch,
            client_payload,
            enterprise: None,
            installation: Box::new(installation),
            organization: None,
            repository: Box::new(repository),
            sender: Box::new(sender),
        }
    }
}


