/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WebhookRepositoryRulesetEditedChanges {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<Box<crate::models::WebhookOrganizationRenamedChangesLogin>>,
    #[serde(rename = "enforcement", skip_serializing_if = "Option::is_none")]
    pub enforcement: Option<Box<crate::models::WebhookOrganizationRenamedChangesLogin>>,
    #[serde(rename = "conditions", skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Box<crate::models::WebhookRepositoryRulesetEditedChangesConditions>>,
    #[serde(rename = "rules", skip_serializing_if = "Option::is_none")]
    pub rules: Option<Box<crate::models::WebhookRepositoryRulesetEditedChangesRules>>,
}

impl WebhookRepositoryRulesetEditedChanges {
    pub fn new() -> WebhookRepositoryRulesetEditedChanges {
        WebhookRepositoryRulesetEditedChanges {
            name: None,
            enforcement: None,
            conditions: None,
            rules: None,
        }
    }
}


