/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WorkflowRunUsageBillable {
    #[serde(rename = "UBUNTU", skip_serializing_if = "Option::is_none")]
    pub ubuntu: Option<Box<crate::models::WorkflowRunUsageBillableUbuntu>>,
    #[serde(rename = "MACOS", skip_serializing_if = "Option::is_none")]
    pub macos: Option<Box<crate::models::WorkflowRunUsageBillableUbuntu>>,
    #[serde(rename = "WINDOWS", skip_serializing_if = "Option::is_none")]
    pub windows: Option<Box<crate::models::WorkflowRunUsageBillableUbuntu>>,
}

impl WorkflowRunUsageBillable {
    pub fn new() -> WorkflowRunUsageBillable {
        WorkflowRunUsageBillable {
            ubuntu: None,
            macos: None,
            windows: None,
        }
    }
}


