=begin
#GitHub v3 REST API

#GitHub's v3 REST API.

The version of the OpenAPI document: 1.1.4

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.0

=end

require 'date'
require 'time'

module OpenapiClient
  # Details of a Personal Access Token Request.
  class PersonalAccessTokenRequest
    # Unique identifier of the request for access via fine-grained personal access token. Used as the `pat_request_id` parameter in the list and review API calls.
    attr_accessor :id

    attr_accessor :owner

    attr_accessor :permissions_added

    attr_accessor :permissions_upgraded

    attr_accessor :permissions_result

    # Type of repository selection requested.
    attr_accessor :repository_selection

    # The number of repositories the token is requesting access to. This field is only populated when `repository_selection` is `subset`.
    attr_accessor :repository_count

    # An array of repository objects the token is requesting access to. This field is only populated when `repository_selection` is `subset`.
    attr_accessor :repositories

    # Date and time when the request for access was created.
    attr_accessor :created_at

    # Whether the associated fine-grained personal access token has expired.
    attr_accessor :token_expired

    # Date and time when the associated fine-grained personal access token expires.
    attr_accessor :token_expires_at

    # Date and time when the associated fine-grained personal access token was last used for authentication.
    attr_accessor :token_last_used_at

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'owner' => :'owner',
        :'permissions_added' => :'permissions_added',
        :'permissions_upgraded' => :'permissions_upgraded',
        :'permissions_result' => :'permissions_result',
        :'repository_selection' => :'repository_selection',
        :'repository_count' => :'repository_count',
        :'repositories' => :'repositories',
        :'created_at' => :'created_at',
        :'token_expired' => :'token_expired',
        :'token_expires_at' => :'token_expires_at',
        :'token_last_used_at' => :'token_last_used_at'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Integer',
        :'owner' => :'SimpleUser',
        :'permissions_added' => :'PersonalAccessTokenRequestPermissionsAdded',
        :'permissions_upgraded' => :'PersonalAccessTokenRequestPermissionsUpgraded',
        :'permissions_result' => :'PersonalAccessTokenRequestPermissionsResult',
        :'repository_selection' => :'String',
        :'repository_count' => :'Integer',
        :'repositories' => :'Array<WebhooksRepositoriesInner>',
        :'created_at' => :'String',
        :'token_expired' => :'Boolean',
        :'token_expires_at' => :'String',
        :'token_last_used_at' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'repository_count',
        :'repositories',
        :'token_expires_at',
        :'token_last_used_at'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::PersonalAccessTokenRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::PersonalAccessTokenRequest`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'owner')
        self.owner = attributes[:'owner']
      end

      if attributes.key?(:'permissions_added')
        self.permissions_added = attributes[:'permissions_added']
      end

      if attributes.key?(:'permissions_upgraded')
        self.permissions_upgraded = attributes[:'permissions_upgraded']
      end

      if attributes.key?(:'permissions_result')
        self.permissions_result = attributes[:'permissions_result']
      end

      if attributes.key?(:'repository_selection')
        self.repository_selection = attributes[:'repository_selection']
      end

      if attributes.key?(:'repository_count')
        self.repository_count = attributes[:'repository_count']
      end

      if attributes.key?(:'repositories')
        if (value = attributes[:'repositories']).is_a?(Array)
          self.repositories = value
        end
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'token_expired')
        self.token_expired = attributes[:'token_expired']
      end

      if attributes.key?(:'token_expires_at')
        self.token_expires_at = attributes[:'token_expires_at']
      end

      if attributes.key?(:'token_last_used_at')
        self.token_last_used_at = attributes[:'token_last_used_at']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @owner.nil?
        invalid_properties.push('invalid value for "owner", owner cannot be nil.')
      end

      if @permissions_added.nil?
        invalid_properties.push('invalid value for "permissions_added", permissions_added cannot be nil.')
      end

      if @permissions_upgraded.nil?
        invalid_properties.push('invalid value for "permissions_upgraded", permissions_upgraded cannot be nil.')
      end

      if @permissions_result.nil?
        invalid_properties.push('invalid value for "permissions_result", permissions_result cannot be nil.')
      end

      if @repository_selection.nil?
        invalid_properties.push('invalid value for "repository_selection", repository_selection cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @token_expired.nil?
        invalid_properties.push('invalid value for "token_expired", token_expired cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @id.nil?
      return false if @owner.nil?
      return false if @permissions_added.nil?
      return false if @permissions_upgraded.nil?
      return false if @permissions_result.nil?
      return false if @repository_selection.nil?
      repository_selection_validator = EnumAttributeValidator.new('String', ["none", "all", "subset"])
      return false unless repository_selection_validator.valid?(@repository_selection)
      return false if @created_at.nil?
      return false if @token_expired.nil?
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] repository_selection Object to be assigned
    def repository_selection=(repository_selection)
      validator = EnumAttributeValidator.new('String', ["none", "all", "subset"])
      unless validator.valid?(repository_selection)
        fail ArgumentError, "invalid value for \"repository_selection\", must be one of #{validator.allowable_values}."
      end
      @repository_selection = repository_selection
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          owner == o.owner &&
          permissions_added == o.permissions_added &&
          permissions_upgraded == o.permissions_upgraded &&
          permissions_result == o.permissions_result &&
          repository_selection == o.repository_selection &&
          repository_count == o.repository_count &&
          repositories == o.repositories &&
          created_at == o.created_at &&
          token_expired == o.token_expired &&
          token_expires_at == o.token_expires_at &&
          token_last_used_at == o.token_last_used_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, owner, permissions_added, permissions_upgraded, permissions_result, repository_selection, repository_count, repositories, created_at, token_expired, token_expires_at, token_last_used_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
