=begin
#GitHub v3 REST API

#GitHub's v3 REST API.

The version of the OpenAPI document: 1.1.4

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.0

=end

require 'date'
require 'time'

module OpenapiClient
  class PullRequestWebhook
    attr_accessor :url

    attr_accessor :id

    attr_accessor :node_id

    attr_accessor :html_url

    attr_accessor :diff_url

    attr_accessor :patch_url

    attr_accessor :issue_url

    attr_accessor :commits_url

    attr_accessor :review_comments_url

    attr_accessor :review_comment_url

    attr_accessor :comments_url

    attr_accessor :statuses_url

    # Number uniquely identifying the pull request within its repository.
    attr_accessor :number

    # State of this Pull Request. Either `open` or `closed`.
    attr_accessor :state

    attr_accessor :locked

    # The title of the pull request.
    attr_accessor :title

    attr_accessor :user

    attr_accessor :body

    attr_accessor :labels

    attr_accessor :milestone

    attr_accessor :active_lock_reason

    attr_accessor :created_at

    attr_accessor :updated_at

    attr_accessor :closed_at

    attr_accessor :merged_at

    attr_accessor :merge_commit_sha

    attr_accessor :assignee

    attr_accessor :assignees

    attr_accessor :requested_reviewers

    attr_accessor :requested_teams

    attr_accessor :head

    attr_accessor :base

    attr_accessor :_links

    attr_accessor :author_association

    attr_accessor :auto_merge

    # Indicates whether or not the pull request is a draft.
    attr_accessor :draft

    attr_accessor :merged

    attr_accessor :mergeable

    attr_accessor :rebaseable

    attr_accessor :mergeable_state

    attr_accessor :merged_by

    attr_accessor :comments

    attr_accessor :review_comments

    # Indicates whether maintainers can modify the pull request.
    attr_accessor :maintainer_can_modify

    attr_accessor :commits

    attr_accessor :additions

    attr_accessor :deletions

    attr_accessor :changed_files

    # Whether to allow auto-merge for pull requests.
    attr_accessor :allow_auto_merge

    # Whether to allow updating the pull request's branch.
    attr_accessor :allow_update_branch

    # Whether to delete head branches when pull requests are merged.
    attr_accessor :delete_branch_on_merge

    # The default value for a merge commit message. - `PR_TITLE` - default to the pull request's title. - `PR_BODY` - default to the pull request's body. - `BLANK` - default to a blank commit message.
    attr_accessor :merge_commit_message

    # The default value for a merge commit title. - `PR_TITLE` - default to the pull request's title. - `MERGE_MESSAGE` - default to the classic title for a merge message (e.g., \"Merge pull request #123 from branch-name\").
    attr_accessor :merge_commit_title

    # The default value for a squash merge commit message: - `PR_BODY` - default to the pull request's body. - `COMMIT_MESSAGES` - default to the branch's commit messages. - `BLANK` - default to a blank commit message.
    attr_accessor :squash_merge_commit_message

    # The default value for a squash merge commit title: - `PR_TITLE` - default to the pull request's title. - `COMMIT_OR_PR_TITLE` - default to the commit's title (if only one commit) or the pull request's title (when more than one commit).
    attr_accessor :squash_merge_commit_title

    # Whether a squash merge commit can use the pull request title as default. **This property has been deprecated. Please use `squash_merge_commit_title` instead.**
    attr_accessor :use_squash_pr_title_as_default

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'url' => :'url',
        :'id' => :'id',
        :'node_id' => :'node_id',
        :'html_url' => :'html_url',
        :'diff_url' => :'diff_url',
        :'patch_url' => :'patch_url',
        :'issue_url' => :'issue_url',
        :'commits_url' => :'commits_url',
        :'review_comments_url' => :'review_comments_url',
        :'review_comment_url' => :'review_comment_url',
        :'comments_url' => :'comments_url',
        :'statuses_url' => :'statuses_url',
        :'number' => :'number',
        :'state' => :'state',
        :'locked' => :'locked',
        :'title' => :'title',
        :'user' => :'user',
        :'body' => :'body',
        :'labels' => :'labels',
        :'milestone' => :'milestone',
        :'active_lock_reason' => :'active_lock_reason',
        :'created_at' => :'created_at',
        :'updated_at' => :'updated_at',
        :'closed_at' => :'closed_at',
        :'merged_at' => :'merged_at',
        :'merge_commit_sha' => :'merge_commit_sha',
        :'assignee' => :'assignee',
        :'assignees' => :'assignees',
        :'requested_reviewers' => :'requested_reviewers',
        :'requested_teams' => :'requested_teams',
        :'head' => :'head',
        :'base' => :'base',
        :'_links' => :'_links',
        :'author_association' => :'author_association',
        :'auto_merge' => :'auto_merge',
        :'draft' => :'draft',
        :'merged' => :'merged',
        :'mergeable' => :'mergeable',
        :'rebaseable' => :'rebaseable',
        :'mergeable_state' => :'mergeable_state',
        :'merged_by' => :'merged_by',
        :'comments' => :'comments',
        :'review_comments' => :'review_comments',
        :'maintainer_can_modify' => :'maintainer_can_modify',
        :'commits' => :'commits',
        :'additions' => :'additions',
        :'deletions' => :'deletions',
        :'changed_files' => :'changed_files',
        :'allow_auto_merge' => :'allow_auto_merge',
        :'allow_update_branch' => :'allow_update_branch',
        :'delete_branch_on_merge' => :'delete_branch_on_merge',
        :'merge_commit_message' => :'merge_commit_message',
        :'merge_commit_title' => :'merge_commit_title',
        :'squash_merge_commit_message' => :'squash_merge_commit_message',
        :'squash_merge_commit_title' => :'squash_merge_commit_title',
        :'use_squash_pr_title_as_default' => :'use_squash_pr_title_as_default'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'url' => :'String',
        :'id' => :'Integer',
        :'node_id' => :'String',
        :'html_url' => :'String',
        :'diff_url' => :'String',
        :'patch_url' => :'String',
        :'issue_url' => :'String',
        :'commits_url' => :'String',
        :'review_comments_url' => :'String',
        :'review_comment_url' => :'String',
        :'comments_url' => :'String',
        :'statuses_url' => :'String',
        :'number' => :'Integer',
        :'state' => :'String',
        :'locked' => :'Boolean',
        :'title' => :'String',
        :'user' => :'SimpleUser',
        :'body' => :'String',
        :'labels' => :'Array<PullRequestLabelsInner>',
        :'milestone' => :'NullableMilestone',
        :'active_lock_reason' => :'String',
        :'created_at' => :'Time',
        :'updated_at' => :'Time',
        :'closed_at' => :'Time',
        :'merged_at' => :'Time',
        :'merge_commit_sha' => :'String',
        :'assignee' => :'NullableSimpleUser',
        :'assignees' => :'Array<SimpleUser>',
        :'requested_reviewers' => :'Array<SimpleUser>',
        :'requested_teams' => :'Array<TeamSimple>',
        :'head' => :'PullRequestHead',
        :'base' => :'PullRequestBase',
        :'_links' => :'PullRequestSimpleLinks',
        :'author_association' => :'AuthorAssociation',
        :'auto_merge' => :'AutoMerge',
        :'draft' => :'Boolean',
        :'merged' => :'Boolean',
        :'mergeable' => :'Boolean',
        :'rebaseable' => :'Boolean',
        :'mergeable_state' => :'String',
        :'merged_by' => :'NullableSimpleUser',
        :'comments' => :'Integer',
        :'review_comments' => :'Integer',
        :'maintainer_can_modify' => :'Boolean',
        :'commits' => :'Integer',
        :'additions' => :'Integer',
        :'deletions' => :'Integer',
        :'changed_files' => :'Integer',
        :'allow_auto_merge' => :'Boolean',
        :'allow_update_branch' => :'Boolean',
        :'delete_branch_on_merge' => :'Boolean',
        :'merge_commit_message' => :'String',
        :'merge_commit_title' => :'String',
        :'squash_merge_commit_message' => :'String',
        :'squash_merge_commit_title' => :'String',
        :'use_squash_pr_title_as_default' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'body',
        :'milestone',
        :'active_lock_reason',
        :'closed_at',
        :'merged_at',
        :'merge_commit_sha',
        :'assignee',
        :'assignees',
        :'requested_reviewers',
        :'requested_teams',
        :'auto_merge',
        :'mergeable',
        :'rebaseable',
        :'merged_by',
      ])
    end

    # List of class defined in allOf (OpenAPI v3)
    def self.openapi_all_of
      [
      :'PullRequest',
      :'PullRequestWebhookAllOf'
      ]
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::PullRequestWebhook` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::PullRequestWebhook`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'url')
        self.url = attributes[:'url']
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'node_id')
        self.node_id = attributes[:'node_id']
      end

      if attributes.key?(:'html_url')
        self.html_url = attributes[:'html_url']
      end

      if attributes.key?(:'diff_url')
        self.diff_url = attributes[:'diff_url']
      end

      if attributes.key?(:'patch_url')
        self.patch_url = attributes[:'patch_url']
      end

      if attributes.key?(:'issue_url')
        self.issue_url = attributes[:'issue_url']
      end

      if attributes.key?(:'commits_url')
        self.commits_url = attributes[:'commits_url']
      end

      if attributes.key?(:'review_comments_url')
        self.review_comments_url = attributes[:'review_comments_url']
      end

      if attributes.key?(:'review_comment_url')
        self.review_comment_url = attributes[:'review_comment_url']
      end

      if attributes.key?(:'comments_url')
        self.comments_url = attributes[:'comments_url']
      end

      if attributes.key?(:'statuses_url')
        self.statuses_url = attributes[:'statuses_url']
      end

      if attributes.key?(:'number')
        self.number = attributes[:'number']
      end

      if attributes.key?(:'state')
        self.state = attributes[:'state']
      end

      if attributes.key?(:'locked')
        self.locked = attributes[:'locked']
      end

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      end

      if attributes.key?(:'user')
        self.user = attributes[:'user']
      end

      if attributes.key?(:'body')
        self.body = attributes[:'body']
      end

      if attributes.key?(:'labels')
        if (value = attributes[:'labels']).is_a?(Array)
          self.labels = value
        end
      end

      if attributes.key?(:'milestone')
        self.milestone = attributes[:'milestone']
      end

      if attributes.key?(:'active_lock_reason')
        self.active_lock_reason = attributes[:'active_lock_reason']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end

      if attributes.key?(:'closed_at')
        self.closed_at = attributes[:'closed_at']
      end

      if attributes.key?(:'merged_at')
        self.merged_at = attributes[:'merged_at']
      end

      if attributes.key?(:'merge_commit_sha')
        self.merge_commit_sha = attributes[:'merge_commit_sha']
      end

      if attributes.key?(:'assignee')
        self.assignee = attributes[:'assignee']
      end

      if attributes.key?(:'assignees')
        if (value = attributes[:'assignees']).is_a?(Array)
          self.assignees = value
        end
      end

      if attributes.key?(:'requested_reviewers')
        if (value = attributes[:'requested_reviewers']).is_a?(Array)
          self.requested_reviewers = value
        end
      end

      if attributes.key?(:'requested_teams')
        if (value = attributes[:'requested_teams']).is_a?(Array)
          self.requested_teams = value
        end
      end

      if attributes.key?(:'head')
        self.head = attributes[:'head']
      end

      if attributes.key?(:'base')
        self.base = attributes[:'base']
      end

      if attributes.key?(:'_links')
        self._links = attributes[:'_links']
      end

      if attributes.key?(:'author_association')
        self.author_association = attributes[:'author_association']
      end

      if attributes.key?(:'auto_merge')
        self.auto_merge = attributes[:'auto_merge']
      end

      if attributes.key?(:'draft')
        self.draft = attributes[:'draft']
      end

      if attributes.key?(:'merged')
        self.merged = attributes[:'merged']
      end

      if attributes.key?(:'mergeable')
        self.mergeable = attributes[:'mergeable']
      end

      if attributes.key?(:'rebaseable')
        self.rebaseable = attributes[:'rebaseable']
      end

      if attributes.key?(:'mergeable_state')
        self.mergeable_state = attributes[:'mergeable_state']
      end

      if attributes.key?(:'merged_by')
        self.merged_by = attributes[:'merged_by']
      end

      if attributes.key?(:'comments')
        self.comments = attributes[:'comments']
      end

      if attributes.key?(:'review_comments')
        self.review_comments = attributes[:'review_comments']
      end

      if attributes.key?(:'maintainer_can_modify')
        self.maintainer_can_modify = attributes[:'maintainer_can_modify']
      end

      if attributes.key?(:'commits')
        self.commits = attributes[:'commits']
      end

      if attributes.key?(:'additions')
        self.additions = attributes[:'additions']
      end

      if attributes.key?(:'deletions')
        self.deletions = attributes[:'deletions']
      end

      if attributes.key?(:'changed_files')
        self.changed_files = attributes[:'changed_files']
      end

      if attributes.key?(:'allow_auto_merge')
        self.allow_auto_merge = attributes[:'allow_auto_merge']
      else
        self.allow_auto_merge = false
      end

      if attributes.key?(:'allow_update_branch')
        self.allow_update_branch = attributes[:'allow_update_branch']
      end

      if attributes.key?(:'delete_branch_on_merge')
        self.delete_branch_on_merge = attributes[:'delete_branch_on_merge']
      else
        self.delete_branch_on_merge = false
      end

      if attributes.key?(:'merge_commit_message')
        self.merge_commit_message = attributes[:'merge_commit_message']
      end

      if attributes.key?(:'merge_commit_title')
        self.merge_commit_title = attributes[:'merge_commit_title']
      end

      if attributes.key?(:'squash_merge_commit_message')
        self.squash_merge_commit_message = attributes[:'squash_merge_commit_message']
      end

      if attributes.key?(:'squash_merge_commit_title')
        self.squash_merge_commit_title = attributes[:'squash_merge_commit_title']
      end

      if attributes.key?(:'use_squash_pr_title_as_default')
        self.use_squash_pr_title_as_default = attributes[:'use_squash_pr_title_as_default']
      else
        self.use_squash_pr_title_as_default = false
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @url.nil?
        invalid_properties.push('invalid value for "url", url cannot be nil.')
      end

      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @node_id.nil?
        invalid_properties.push('invalid value for "node_id", node_id cannot be nil.')
      end

      if @html_url.nil?
        invalid_properties.push('invalid value for "html_url", html_url cannot be nil.')
      end

      if @diff_url.nil?
        invalid_properties.push('invalid value for "diff_url", diff_url cannot be nil.')
      end

      if @patch_url.nil?
        invalid_properties.push('invalid value for "patch_url", patch_url cannot be nil.')
      end

      if @issue_url.nil?
        invalid_properties.push('invalid value for "issue_url", issue_url cannot be nil.')
      end

      if @commits_url.nil?
        invalid_properties.push('invalid value for "commits_url", commits_url cannot be nil.')
      end

      if @review_comments_url.nil?
        invalid_properties.push('invalid value for "review_comments_url", review_comments_url cannot be nil.')
      end

      if @review_comment_url.nil?
        invalid_properties.push('invalid value for "review_comment_url", review_comment_url cannot be nil.')
      end

      if @comments_url.nil?
        invalid_properties.push('invalid value for "comments_url", comments_url cannot be nil.')
      end

      if @statuses_url.nil?
        invalid_properties.push('invalid value for "statuses_url", statuses_url cannot be nil.')
      end

      if @number.nil?
        invalid_properties.push('invalid value for "number", number cannot be nil.')
      end

      if @state.nil?
        invalid_properties.push('invalid value for "state", state cannot be nil.')
      end

      if @locked.nil?
        invalid_properties.push('invalid value for "locked", locked cannot be nil.')
      end

      if @title.nil?
        invalid_properties.push('invalid value for "title", title cannot be nil.')
      end

      if @user.nil?
        invalid_properties.push('invalid value for "user", user cannot be nil.')
      end

      if @labels.nil?
        invalid_properties.push('invalid value for "labels", labels cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      if @head.nil?
        invalid_properties.push('invalid value for "head", head cannot be nil.')
      end

      if @base.nil?
        invalid_properties.push('invalid value for "base", base cannot be nil.')
      end

      if @_links.nil?
        invalid_properties.push('invalid value for "_links", _links cannot be nil.')
      end

      if @author_association.nil?
        invalid_properties.push('invalid value for "author_association", author_association cannot be nil.')
      end

      if @merged.nil?
        invalid_properties.push('invalid value for "merged", merged cannot be nil.')
      end

      if @mergeable_state.nil?
        invalid_properties.push('invalid value for "mergeable_state", mergeable_state cannot be nil.')
      end

      if @comments.nil?
        invalid_properties.push('invalid value for "comments", comments cannot be nil.')
      end

      if @review_comments.nil?
        invalid_properties.push('invalid value for "review_comments", review_comments cannot be nil.')
      end

      if @maintainer_can_modify.nil?
        invalid_properties.push('invalid value for "maintainer_can_modify", maintainer_can_modify cannot be nil.')
      end

      if @commits.nil?
        invalid_properties.push('invalid value for "commits", commits cannot be nil.')
      end

      if @additions.nil?
        invalid_properties.push('invalid value for "additions", additions cannot be nil.')
      end

      if @deletions.nil?
        invalid_properties.push('invalid value for "deletions", deletions cannot be nil.')
      end

      if @changed_files.nil?
        invalid_properties.push('invalid value for "changed_files", changed_files cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @url.nil?
      return false if @id.nil?
      return false if @node_id.nil?
      return false if @html_url.nil?
      return false if @diff_url.nil?
      return false if @patch_url.nil?
      return false if @issue_url.nil?
      return false if @commits_url.nil?
      return false if @review_comments_url.nil?
      return false if @review_comment_url.nil?
      return false if @comments_url.nil?
      return false if @statuses_url.nil?
      return false if @number.nil?
      return false if @state.nil?
      state_validator = EnumAttributeValidator.new('String', ["open", "closed"])
      return false unless state_validator.valid?(@state)
      return false if @locked.nil?
      return false if @title.nil?
      return false if @user.nil?
      return false if @labels.nil?
      return false if @created_at.nil?
      return false if @updated_at.nil?
      return false if @head.nil?
      return false if @base.nil?
      return false if @_links.nil?
      return false if @author_association.nil?
      return false if @merged.nil?
      return false if @mergeable_state.nil?
      return false if @comments.nil?
      return false if @review_comments.nil?
      return false if @maintainer_can_modify.nil?
      return false if @commits.nil?
      return false if @additions.nil?
      return false if @deletions.nil?
      return false if @changed_files.nil?
      merge_commit_message_validator = EnumAttributeValidator.new('String', ["PR_BODY", "PR_TITLE", "BLANK"])
      return false unless merge_commit_message_validator.valid?(@merge_commit_message)
      merge_commit_title_validator = EnumAttributeValidator.new('String', ["PR_TITLE", "MERGE_MESSAGE"])
      return false unless merge_commit_title_validator.valid?(@merge_commit_title)
      squash_merge_commit_message_validator = EnumAttributeValidator.new('String', ["PR_BODY", "COMMIT_MESSAGES", "BLANK"])
      return false unless squash_merge_commit_message_validator.valid?(@squash_merge_commit_message)
      squash_merge_commit_title_validator = EnumAttributeValidator.new('String', ["PR_TITLE", "COMMIT_OR_PR_TITLE"])
      return false unless squash_merge_commit_title_validator.valid?(@squash_merge_commit_title)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] state Object to be assigned
    def state=(state)
      validator = EnumAttributeValidator.new('String', ["open", "closed"])
      unless validator.valid?(state)
        fail ArgumentError, "invalid value for \"state\", must be one of #{validator.allowable_values}."
      end
      @state = state
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] merge_commit_message Object to be assigned
    def merge_commit_message=(merge_commit_message)
      validator = EnumAttributeValidator.new('String', ["PR_BODY", "PR_TITLE", "BLANK"])
      unless validator.valid?(merge_commit_message)
        fail ArgumentError, "invalid value for \"merge_commit_message\", must be one of #{validator.allowable_values}."
      end
      @merge_commit_message = merge_commit_message
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] merge_commit_title Object to be assigned
    def merge_commit_title=(merge_commit_title)
      validator = EnumAttributeValidator.new('String', ["PR_TITLE", "MERGE_MESSAGE"])
      unless validator.valid?(merge_commit_title)
        fail ArgumentError, "invalid value for \"merge_commit_title\", must be one of #{validator.allowable_values}."
      end
      @merge_commit_title = merge_commit_title
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] squash_merge_commit_message Object to be assigned
    def squash_merge_commit_message=(squash_merge_commit_message)
      validator = EnumAttributeValidator.new('String', ["PR_BODY", "COMMIT_MESSAGES", "BLANK"])
      unless validator.valid?(squash_merge_commit_message)
        fail ArgumentError, "invalid value for \"squash_merge_commit_message\", must be one of #{validator.allowable_values}."
      end
      @squash_merge_commit_message = squash_merge_commit_message
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] squash_merge_commit_title Object to be assigned
    def squash_merge_commit_title=(squash_merge_commit_title)
      validator = EnumAttributeValidator.new('String', ["PR_TITLE", "COMMIT_OR_PR_TITLE"])
      unless validator.valid?(squash_merge_commit_title)
        fail ArgumentError, "invalid value for \"squash_merge_commit_title\", must be one of #{validator.allowable_values}."
      end
      @squash_merge_commit_title = squash_merge_commit_title
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          url == o.url &&
          id == o.id &&
          node_id == o.node_id &&
          html_url == o.html_url &&
          diff_url == o.diff_url &&
          patch_url == o.patch_url &&
          issue_url == o.issue_url &&
          commits_url == o.commits_url &&
          review_comments_url == o.review_comments_url &&
          review_comment_url == o.review_comment_url &&
          comments_url == o.comments_url &&
          statuses_url == o.statuses_url &&
          number == o.number &&
          state == o.state &&
          locked == o.locked &&
          title == o.title &&
          user == o.user &&
          body == o.body &&
          labels == o.labels &&
          milestone == o.milestone &&
          active_lock_reason == o.active_lock_reason &&
          created_at == o.created_at &&
          updated_at == o.updated_at &&
          closed_at == o.closed_at &&
          merged_at == o.merged_at &&
          merge_commit_sha == o.merge_commit_sha &&
          assignee == o.assignee &&
          assignees == o.assignees &&
          requested_reviewers == o.requested_reviewers &&
          requested_teams == o.requested_teams &&
          head == o.head &&
          base == o.base &&
          _links == o._links &&
          author_association == o.author_association &&
          auto_merge == o.auto_merge &&
          draft == o.draft &&
          merged == o.merged &&
          mergeable == o.mergeable &&
          rebaseable == o.rebaseable &&
          mergeable_state == o.mergeable_state &&
          merged_by == o.merged_by &&
          comments == o.comments &&
          review_comments == o.review_comments &&
          maintainer_can_modify == o.maintainer_can_modify &&
          commits == o.commits &&
          additions == o.additions &&
          deletions == o.deletions &&
          changed_files == o.changed_files &&
          allow_auto_merge == o.allow_auto_merge &&
          allow_update_branch == o.allow_update_branch &&
          delete_branch_on_merge == o.delete_branch_on_merge &&
          merge_commit_message == o.merge_commit_message &&
          merge_commit_title == o.merge_commit_title &&
          squash_merge_commit_message == o.squash_merge_commit_message &&
          squash_merge_commit_title == o.squash_merge_commit_title &&
          use_squash_pr_title_as_default == o.use_squash_pr_title_as_default
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [url, id, node_id, html_url, diff_url, patch_url, issue_url, commits_url, review_comments_url, review_comment_url, comments_url, statuses_url, number, state, locked, title, user, body, labels, milestone, active_lock_reason, created_at, updated_at, closed_at, merged_at, merge_commit_sha, assignee, assignees, requested_reviewers, requested_teams, head, base, _links, author_association, auto_merge, draft, merged, mergeable, rebaseable, mergeable_state, merged_by, comments, review_comments, maintainer_can_modify, commits, additions, deletions, changed_files, allow_auto_merge, allow_update_branch, delete_branch_on_merge, merge_commit_message, merge_commit_title, squash_merge_commit_message, squash_merge_commit_title, use_squash_pr_title_as_default].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
