=begin
#GitHub v3 REST API

#GitHub's v3 REST API.

The version of the OpenAPI document: 1.1.4

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::WebhooksSecurityAdvisoryIdentifiersInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::WebhooksSecurityAdvisoryIdentifiersInner do
  let(:instance) { OpenapiClient::WebhooksSecurityAdvisoryIdentifiersInner.new }

  describe 'test an instance of WebhooksSecurityAdvisoryIdentifiersInner' do
    it 'should create an instance of WebhooksSecurityAdvisoryIdentifiersInner' do
      expect(instance).to be_instance_of(OpenapiClient::WebhooksSecurityAdvisoryIdentifiersInner)
    end
  end
  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "value"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
